# This make the database persistent.
volumes:
  postgres-data-hikari:
    driver: local

services:
  postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    container_name: database
    volumes:
      - "postgres-data-hikari:/var/lib/postgresql/data"
    restart: 'always'
    ports:
      - "${DB_EXPOSED_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
