spring:
  application:
    name: hikari-example
  datasource:
    url: jdbc:h2:mem:hxdb;NON_KEYWORDS=user
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: HxHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 2000
      validation-timeout: 5000
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          globally_quoted_identifiers: true

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
