spring:
  application:
    name: hikari-example
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HxHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 2000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      start:
        command: up
      stop:
        command: down

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      jdbc: true

logging:
  level:
    com.zaxxer.hikari.pool.*: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    o.h.r.j.i.ResourceRegistryStandardImpl: TRACE
    o.s.orm.jpa.JpaTransactionManager: TRACE
    org.hibernate.internal.SessionImpl: TRACE
    o.h.engine.jdbc.spi.SqlExceptionHelper: TRACE
    java.sql.SQLTransientConnectionException: TRACE

    org:
      hibernate:
        SQL: INFO
        orm:
          jdbc:
            bind: INFO
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: INFO
